# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packDestination: '$(Build.SourcesDirectory)'

- task: DownloadSecureFile@1
  inputs:
    secureFile: 'NuGetTestDeveloper1.pfx'

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '21297ca9-7b65-487d-9bc5-dd78bbf02267/7af5a2c8-9d02-4be6-af56-faf8507c885a'
    allowPackageConflicts: true

