# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
# Package a project
- task: UiPathPack@4
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)'
    orchestratorConnection: 'UiPathOrchestratorConnection'
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'

- task: DownloadSecureFile@1
  name: cert
  inputs:
    secureFile: 'NuGetTestDeveloper1.pfx'

- script: |
    echo Installing $(caCertificate.secureFilePath) to the trusted CA directory...

- task: NuGetCommand@2
  inputs:
    command: 'custom'
    arguments: 'sign $(Build.ArtifactStagingDirectory)\Output/**/*.nupkg -CertificatePath $(cert.secureFilePath) -CertificatePassword 1234' 

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)\Output/**/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '21297ca9-7b65-487d-9bc5-dd78bbf02267/7af5a2c8-9d02-4be6-af56-faf8507c885a'

- task: UiPathDeploy@4
  inputs:
    orchestratorConnection: 'UiPathOrchestratorConnection'
    packagesPath: '$(Build.ArtifactStagingDirectory)\Output'
    folderName: 'AzureDevOpsFolder'